"""Made revision

Revision ID: 966650047e8c
Revises: 969fa271fc3f
Create Date: 2024-01-23 10:17:57.185062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966650047e8c'
down_revision = '969fa271fc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(length=100), nullable=False))
        batch_op.drop_column('price')

    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
